import './icon-arrow-drop.svg';
import './icon-arrow-left.svg';
import './icon-arrow-more.svg';
import './icon-arrow-right.svg';
import './icon-close.svg';
import './icon-contents.svg';
import './icon-mail.svg';
import './icon-phone.svg';
import './icon-search.svg';
