type ProjectAwards = {
  ij: boolean;
  esg: boolean;
};

type ProjectStatus = 'current' | 'done';
type ProjectCategory = 'esg' | 'ppp' | 'mega';

type Project = {
  id: number;
  title: string;
  amount: { value: number; unit: string };
  bank: { value: number; unit: string };
  country: { name: string; code: string; flag: string };
  year: number;
  type: number;
  industries: number[];
  partner: string;
  participation: string;
  status: ProjectStatus;
  category: ProjectCategory;
  awards: ProjectAwards;
  image: string;
};

const PROJECTS: Project[] = [
  {
    id: 1,
    title:
      'Предоставление ОАО «Араратбанк» невозобновляемой целевой кредитной линии для&nbsp;реализации программы&nbsp;...',
    amount: { value: 388, unit: 'млн&nbsp;$' },
    bank: { value: 300, unit: 'млн&nbsp;$' },
    country: {
      name: 'Армения',
      code: 'am',
      flag: '/assets/images/flags/flag-am.svg',
    },
    year: 2024,
    type: 1,
    industries: [5],
    partner: 'ОАО «Араратбанк»',
    participation: 'Частный',
    status: 'current',
    category: 'esg',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 2,
    title:
      'Предоставление кредитной линии ОАО «Айыл банк» для&nbsp;реализации программы микрофинансирования в&nbsp;Кыргызской Республике',
    amount: { value: 388, unit: 'млн&nbsp;$' },
    bank: { value: 300, unit: 'млн&nbsp;$' },
    country: {
      name: 'Кыргызстан',
      code: 'kg',
      flag: '/assets/images/flags/flag-kg.svg',
    },
    year: 2024,
    type: 1,
    industries: [5],
    partner: 'ОАО «Айыл банк»',
    participation: 'Частный',
    status: 'current',
    category: 'esg',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 3,
    title: 'Расширение и&nbsp;модернизация Международного аэропорта Алматы',
    amount: { value: 512, unit: 'млн&nbsp;$' },
    bank: { value: 410, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2023,
    type: 3,
    industries: [3, 6],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 4,
    title:
      'Производство молочной и&nbsp;мясной продукции полного цикла в&nbsp;Армении',
    amount: { value: 210, unit: 'млн&nbsp;$' },
    bank: { value: 150, unit: 'млн&nbsp;$' },
    country: {
      name: 'Армения',
      code: 'am',
      flag: '/assets/images/flags/flag-am.svg',
    },
    year: 2022,
    type: 3,
    industries: [6],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 5,
    title:
      'Строительство ветропарка мощностью 100&nbsp;МВт в&nbsp;Карагандинской области',
    amount: { value: 640, unit: 'млн&nbsp;$' },
    bank: { value: 500, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2024,
    type: 3,
    industries: [4],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'esg',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 6,
    title: 'Модернизация металлургического комбината в&nbsp;Темиртау',
    amount: { value: 720, unit: 'млн&nbsp;$' },
    bank: { value: 480, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2021,
    type: 4,
    industries: [1],
    partner: '-',
    participation: 'Смешанный',
    status: 'done',
    category: 'mega',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 7,
    title:
      'Гарантия по&nbsp;программе развития транспортного коридора «Север&nbsp;— Юг»',
    amount: { value: 900, unit: 'млн&nbsp;$' },
    bank: { value: 600, unit: 'млн&nbsp;$' },
    country: {
      name: 'Россия',
      code: 'ru',
      flag: '/assets/images/flags/flag-ru.svg',
    },
    year: 2023,
    type: 2,
    industries: [3],
    partner: '-',
    participation: 'Государственный',
    status: 'current',
    category: 'mega',
    awards: { ij: true, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 8,
    title:
      'Финансирование разработки месторождения полезных ископаемых в&nbsp;Таджикистане',
    amount: { value: 340, unit: 'млн&nbsp;$' },
    bank: { value: 250, unit: 'млн&nbsp;$' },
    country: {
      name: 'Таджикистан',
      code: 'tj',
      flag: '/assets/images/flags/flag-tj.svg',
    },
    year: 2022,
    type: 3,
    industries: [2],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 9,
    title: 'Кредитная линия для&nbsp;агропромышленного комплекса Узбекистана',
    amount: { value: 280, unit: 'млн&nbsp;$' },
    bank: { value: 200, unit: 'млн&nbsp;$' },
    country: {
      name: 'Узбекистан',
      code: 'uz',
      flag: '/assets/images/flags/flag-uz.svg',
    },
    year: 2024,
    type: 1,
    industries: [6],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 10,
    title: 'Строительство гидроэлектростанции на&nbsp;реке Вахш',
    amount: { value: 1100, unit: 'млн&nbsp;$' },
    bank: { value: 800, unit: 'млн&nbsp;$' },
    country: {
      name: 'Таджикистан',
      code: 'tj',
      flag: '/assets/images/flags/flag-tj.svg',
    },
    year: 2020,
    type: 3,
    industries: [4],
    partner: '-',
    participation: 'Смешанный',
    status: 'done',
    category: 'mega',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 11,
    title: 'Развитие инфраструктуры особой экономической зоны в&nbsp;Беларуси',
    amount: { value: 460, unit: 'млн&nbsp;$' },
    bank: { value: 320, unit: 'млн&nbsp;$' },
    country: {
      name: 'Беларусь',
      code: 'by',
      flag: '/assets/images/flags/flag-by.svg',
    },
    year: 2023,
    type: 4,
    industries: [6],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 12,
    title: 'Модернизация энергосетей в&nbsp;Кыргызской Республике',
    amount: { value: 390, unit: 'млн&nbsp;$' },
    bank: { value: 300, unit: 'млн&nbsp;$' },
    country: {
      name: 'Кыргызстан',
      code: 'kg',
      flag: '/assets/images/flags/flag-kg.svg',
    },
    year: 2021,
    type: 1,
    industries: [4],
    partner: '-',
    participation: 'Государственный',
    status: 'done',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 13,
    title:
      'Финансирование лизинговой программы для&nbsp;транспортных компаний России',
    amount: { value: 550, unit: 'млн&nbsp;$' },
    bank: { value: 400, unit: 'млн&nbsp;$' },
    country: {
      name: 'Россия',
      code: 'ru',
      flag: '/assets/images/flags/flag-ru.svg',
    },
    year: 2024,
    type: 5,
    industries: [3, 5],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 14,
    title: 'Реконструкция железнодорожного узла в&nbsp;Астане',
    amount: { value: 680, unit: 'млн&nbsp;$' },
    bank: { value: 520, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2022,
    type: 3,
    industries: [3],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'mega',
    awards: { ij: true, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 15,
    title:
      'Кредитная линия для&nbsp;поддержки экспорта металлургической продукции',
    amount: { value: 430, unit: 'млн&nbsp;$' },
    bank: { value: 300, unit: 'млн&nbsp;$' },
    country: {
      name: 'Россия',
      code: 'ru',
      flag: '/assets/images/flags/flag-ru.svg',
    },
    year: 2023,
    type: 1,
    industries: [1, 5],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 16,
    title: 'Развитие сети микрофинансирования в&nbsp;Армении',
    amount: { value: 220, unit: 'млн&nbsp;$' },
    bank: { value: 160, unit: 'млн&nbsp;$' },
    country: {
      name: 'Армения',
      code: 'am',
      flag: '/assets/images/flags/flag-am.svg',
    },
    year: 2021,
    type: 1,
    industries: [5],
    partner: '-',
    participation: 'Частный',
    status: 'done',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 17,
    title: 'Строительство солнечной электростанции в&nbsp;Узбекистане',
    amount: { value: 590, unit: 'млн&nbsp;$' },
    bank: { value: 450, unit: 'млн&nbsp;$' },
    country: {
      name: 'Узбекистан',
      code: 'uz',
      flag: '/assets/images/flags/flag-uz.svg',
    },
    year: 2024,
    type: 3,
    industries: [4],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'esg',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 18,
    title:
      'Финансирование добычи и&nbsp;переработки полезных ископаемых в&nbsp;Казахстане',
    amount: { value: 770, unit: 'млн&nbsp;$' },
    bank: { value: 540, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2020,
    type: 3,
    industries: [2],
    partner: '-',
    participation: 'Частный',
    status: 'done',
    category: 'mega',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 19,
    title: 'Гарантийная поддержка инфраструктурного проекта в&nbsp;Минске',
    amount: { value: 360, unit: 'млн&nbsp;$' },
    bank: { value: 240, unit: 'млн&nbsp;$' },
    country: {
      name: 'Беларусь',
      code: 'by',
      flag: '/assets/images/flags/flag-by.svg',
    },
    year: 2022,
    type: 2,
    industries: [6],
    partner: '-',
    participation: 'Государственный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 20,
    title: 'Кредитная линия для&nbsp;модернизации портовой инфраструктуры',
    amount: { value: 820, unit: 'млн&nbsp;$' },
    bank: { value: 600, unit: 'млн&nbsp;$' },
    country: {
      name: 'Россия',
      code: 'ru',
      flag: '/assets/images/flags/flag-ru.svg',
    },
    year: 2023,
    type: 1,
    industries: [3, 6],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'mega',
    awards: { ij: true, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 21,
    title: 'Развитие финансового сектора Кыргызстана через банки-партнёры',
    amount: { value: 300, unit: 'млн&nbsp;$' },
    bank: { value: 230, unit: 'млн&nbsp;$' },
    country: {
      name: 'Кыргызстан',
      code: 'kg',
      flag: '/assets/images/flags/flag-kg.svg',
    },
    year: 2024,
    type: 5,
    industries: [5],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 22,
    title: 'Софинансирование строительства автодороги Душанбе&nbsp;— Бохтар',
    amount: { value: 480, unit: 'млн&nbsp;$' },
    bank: { value: 350, unit: 'млн&nbsp;$' },
    country: {
      name: 'Таджикистан',
      code: 'tj',
      flag: '/assets/images/flags/flag-tj.svg',
    },
    year: 2021,
    type: 4,
    industries: [3],
    partner: '-',
    participation: 'Смешанный',
    status: 'done',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 23,
    title:
      'Инвестиция в&nbsp;производство строительных материалов в&nbsp;Узбекистане',
    amount: { value: 260, unit: 'млн&nbsp;$' },
    bank: { value: 180, unit: 'млн&nbsp;$' },
    country: {
      name: 'Узбекистан',
      code: 'uz',
      flag: '/assets/images/flags/flag-uz.svg',
    },
    year: 2022,
    type: 3,
    industries: [6],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 24,
    title:
      'Кредитная линия для&nbsp;развития зелёной энергетики в&nbsp;Армении',
    amount: { value: 410, unit: 'млн&nbsp;$' },
    bank: { value: 320, unit: 'млн&nbsp;$' },
    country: {
      name: 'Армения',
      code: 'am',
      flag: '/assets/images/flags/flag-am.svg',
    },
    year: 2024,
    type: 1,
    industries: [4],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'esg',
    awards: { ij: true, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 25,
    title: 'Модернизация теплоэлектроцентрали в&nbsp;Карагандинской области',
    amount: { value: 700, unit: 'млн&nbsp;$' },
    bank: { value: 510, unit: 'млн&nbsp;$' },
    country: {
      name: 'Казахстан',
      code: 'kz',
      flag: '/assets/images/flags/flag-kz.svg',
    },
    year: 2023,
    type: 3,
    industries: [4],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'mega',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 26,
    title: 'Финансирование транспортно-логистического центра в&nbsp;Беларуси',
    amount: { value: 520, unit: 'млн&nbsp;$' },
    bank: { value: 380, unit: 'млн&nbsp;$' },
    country: {
      name: 'Беларусь',
      code: 'by',
      flag: '/assets/images/flags/flag-by.svg',
    },
    year: 2024,
    type: 5,
    industries: [3, 6],
    partner: '-',
    participation: 'Смешанный',
    status: 'current',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 27,
    title: 'Гарантия по&nbsp;кредиту на&nbsp;развитие горнодобывающей отрасли',
    amount: { value: 640, unit: 'млн&nbsp;$' },
    bank: { value: 470, unit: 'млн&nbsp;$' },
    country: {
      name: 'Таджикистан',
      code: 'tj',
      flag: '/assets/images/flags/flag-tj.svg',
    },
    year: 2020,
    type: 2,
    industries: [2],
    partner: '-',
    participation: 'Государственный',
    status: 'done',
    category: 'ppp',
    awards: { ij: false, esg: false },
    image: '/assets/images/1200x800.svg',
  },
  {
    id: 28,
    title:
      'Кредитная линия для&nbsp;агросектора и&nbsp;переработки в&nbsp;России',
    amount: { value: 350, unit: 'млн&nbsp;$' },
    bank: { value: 260, unit: 'млн&nbsp;$' },
    country: {
      name: 'Россия',
      code: 'ru',
      flag: '/assets/images/flags/flag-ru.svg',
    },
    year: 2022,
    type: 1,
    industries: [6],
    partner: '-',
    participation: 'Частный',
    status: 'current',
    category: 'esg',
    awards: { ij: false, esg: true },
    image: '/assets/images/1200x800.svg',
  },
];

export { PROJECTS, type Project };
